/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Snapshot = IDL.Record({
  'id' : IDL.Text,
  'eps' : IDL.Float64,
  'sharePrice' : IDL.Float64,
  'totalAssets' : IDL.Float64,
  'ebitda' : IDL.Float64,
  'revenue' : IDL.Float64,
  'interestExpense' : IDL.Float64,
  'currentAssets' : IDL.Float64,
  'bookValuePerShare' : IDL.Float64,
  'grossProfit' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'cogs' : IDL.Float64,
  'ebit' : IDL.Float64,
  'inventory' : IDL.Float64,
  'name' : IDL.Text,
  'currentLiabilities' : IDL.Float64,
  'totalEquity' : IDL.Float64,
  'enterpriseValue' : IDL.Float64,
  'netIncome' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSnapshot' : IDL.Func([IDL.Text], [], []),
  'getBookmarks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSnapshots' : IDL.Func([], [IDL.Vec(Snapshot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSnapshot' : IDL.Func([Snapshot], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Snapshot = IDL.Record({
    'id' : IDL.Text,
    'eps' : IDL.Float64,
    'sharePrice' : IDL.Float64,
    'totalAssets' : IDL.Float64,
    'ebitda' : IDL.Float64,
    'revenue' : IDL.Float64,
    'interestExpense' : IDL.Float64,
    'currentAssets' : IDL.Float64,
    'bookValuePerShare' : IDL.Float64,
    'grossProfit' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'cogs' : IDL.Float64,
    'ebit' : IDL.Float64,
    'inventory' : IDL.Float64,
    'name' : IDL.Text,
    'currentLiabilities' : IDL.Float64,
    'totalEquity' : IDL.Float64,
    'enterpriseValue' : IDL.Float64,
    'netIncome' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSnapshot' : IDL.Func([IDL.Text], [], []),
    'getBookmarks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSnapshots' : IDL.Func([], [IDL.Vec(Snapshot)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSnapshot' : IDL.Func([Snapshot], [], []),
  });
};

export const init = ({ IDL }) => { return []; };