/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Snapshot {
  'id' : string,
  'eps' : number,
  'sharePrice' : number,
  'totalAssets' : number,
  'ebitda' : number,
  'revenue' : number,
  'interestExpense' : number,
  'currentAssets' : number,
  'bookValuePerShare' : number,
  'grossProfit' : number,
  'marketCap' : number,
  'cogs' : number,
  'ebit' : number,
  'inventory' : number,
  'name' : string,
  'currentLiabilities' : number,
  'totalEquity' : number,
  'enterpriseValue' : number,
  'netIncome' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSnapshot' : ActorMethod<[string], undefined>,
  'getBookmarks' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSnapshots' : ActorMethod<[], Array<Snapshot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeBookmark' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSnapshot' : ActorMethod<[Snapshot], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];